version: '3.8'

services:
  web:
    build: .
    container_name: php_web_app
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - phpnet

  db:
    image: mysql:5.7
    container_name: php_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sampledb
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - phpnet

volumes:
  db_data:

networks:
  phpnet:
